In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a=np.array([[1,2,3],[5,6,7]])
print(a)

[[1 2 3]
 [5 6 7]]


In [4]:
#min dimensions
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [5]:
#dtype parameter
a=np.array([1,2,3], dtype=complex) #complex number
print(a)

[1.+0.j 2.+0.j 3.+0.j]
