In [ ]:
import numpy as np

In [ ]:
#shape
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
#reshaping
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#ndim
a=np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [ ]:
b=a.reshape(2,4,3) #3 dimensions
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
#itemsize
x=np.array([1,2,3,4,5], dtype=np.int8)
print(x)
print(x.itemsize) #size of item in bytes

[1 2 3 4 5]
1


In [ ]:
x=np.array([1,2,3,4,5], dtype=np.float32)
print(x)
print(x.itemsize)

[1. 2. 3. 4. 5.]
4
