In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([3,8,7])

In [3]:
print(a+2)

[3 4 5]


In [4]:
print(a+b)

[ 4 10 10]


In [5]:
print(a**2)

[1 4 9]


In [6]:
print(a**b)

[   1  256 2187]


In [7]:
a.mean()

2.0

In [8]:
a.sum()

6

In [9]:
b.sum()

18

In [10]:
#visit numpy.org for more array operations